name: Deploy Cloudflare Worker
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - elyra
      - elyracanvasfinal
    paths:
      - 'api/**'
defaults:
  run:
    working-directory: api
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'api'
